version: '3.9'

services:
  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - 'grafana-configs:/etc/grafana'
      - 'grafana-data:/var/lib/grafana'
    ports:
      - '5621:3000'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - '127.0.0.1:9090:9090'
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    volumes:
      - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "wf-logs:/wf/logs:ro"
    depends_on:
      - prometheus
    links:
      - prometheus
    ports:
      - '127.0.0.1:8125:8125/udp'
      - '127.0.0.1:9273:9273'

  json-exporter:
    image: json-exporter-wf:latest
    volumes:
      - "wf-logs:/app/logs"
    restart: unless-stopped
    
volumes:
  grafana-configs:
  grafana-data:
  wf-logs:
  prometheus-data: